// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  cliContainer: string;
  cliSider: string;
  content: string;
  header: string;
}
export const cssExports: CssExports;
export default cssExports;
